language: go
go:
  - master

before_install:
  - go get -t gopkg.in/yaml.v2
  - go get -t github.com/PolymerGuy/golmes
  - go get -t gonum.org/v1/gonum/...
  - go get -t gopkg.in/yaml.v2
  - go get -t github.com/urfave/cli


script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)